# Generated by Django 3.0 on 2024-02-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taixiu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
